addSbtPlugin("com.dwijnand"       % "sbt-dynver"      % "4.1.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.3")
addSbtPlugin("ch.epfl.scala" % "sbt-scala3-migrate" % "0.5.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"    % "0.9.33")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.4.4")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "1.9.3")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"      % "5.6.0")
