addSbtPlugin("com.dwijnand"       % "sbt-dynver"      % "3.3.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.3.6")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"    % "0.9.4")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"    % "1.5.1")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"      % "5.1.0")
addSbtPlugin("org.wartremover"    % "sbt-wartremover" % "2.4.2")
