addSbtPlugin("com.dwijnand"       % "sbt-dynver"      % "4.0.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.3.7")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"    % "0.9.6")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.0.3")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "1.6.0")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"      % "5.2.0")
addSbtPlugin("org.wartremover"    % "sbt-wartremover" % "2.4.3")
